package auth

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"

	"github.com/deploy-monster/deploy-monster/internal/core"
)

func init() {
	core.RegisterModule(func() core.Module { return New() })
}

// Module implements the authentication module.
type Module struct {
	core   *core.Core
	jwt    *JWTService
	store  core.Store
	logger *slog.Logger
}

// New creates a new authentication module.
func New() *Module {
	return &Module{}
}

func (m *Module) ID() string                  { return "core.auth" }
func (m *Module) Name() string                { return "Authentication" }
func (m *Module) Version() string             { return "1.0.0" }
func (m *Module) Dependencies() []string      { return []string{"core.db"} }
func (m *Module) Events() []core.EventHandler { return nil }

func (m *Module) Init(ctx context.Context, c *core.Core) error {
	m.core = c
	m.logger = c.Logger.With("module", m.ID())

	// Get the Store interface from core
	if c.Store == nil {
		return core.NewAppError(500, "database store not available", nil)
	}
	m.store = c.Store

	// Create JWT service
	m.jwt = NewJWTService(c.Config.Server.SecretKey)

	// First-run setup: create super admin if no users exist
	if err := m.firstRunSetup(ctx); err != nil {
		return err
	}

	return nil
}

func (m *Module) Start(_ context.Context) error {
	m.logger.Info("authentication module started")
	return nil
}

func (m *Module) Stop(_ context.Context) error {
	return nil
}

func (m *Module) Health() core.HealthStatus {
	if m.jwt == nil {
		return core.HealthDown
	}
	return core.HealthOK
}

func (m *Module) Routes() []core.Route {
	return nil // Routes are registered via the API module
}

// JWT returns the JWT service for use by other modules.
func (m *Module) JWT() *JWTService {
	return m.jwt
}

// Store returns the data store for auth-related queries.
func (m *Module) Store() core.Store {
	return m.store
}

// firstRunSetup creates a super admin user and default tenant if no users exist.
func (m *Module) firstRunSetup(ctx context.Context) error {
	count, err := m.store.CountUsers(ctx)
	if err != nil {
		return err
	}
	if count > 0 {
		return nil
	}

	m.logger.Info("first run detected, creating super admin")

	email := getEnvOrDefault("MONSTER_ADMIN_EMAIL", "admin@deploy.monster")
	password := getEnvOrDefault("MONSTER_ADMIN_PASSWORD", "")

	autoGenerated := false
	if password == "" {
		password = core.GeneratePassword(16)
		autoGenerated = true
	}

	hash, err := HashPassword(password)
	if err != nil {
		return err
	}

	// Create default tenant
	tenantID, err2 := m.store.CreateTenantWithDefaults(ctx, "Platform", "platform")
	if err2 != nil {
		return err2
	}

	// Create super admin user
	if _, err3 := m.store.CreateUserWithMembership(ctx, email, hash, "Super Admin", "active", tenantID, "role_super_admin"); err3 != nil {
		return err3
	}

	if autoGenerated {
		// Write credentials to a secure file instead of logging the password
		credPath := filepath.Join(filepath.Dir(m.core.Config.Database.Path), ".credentials")
		content := fmt.Sprintf("email: %s\npassword: %s\n", email, password)
		if err := os.WriteFile(credPath, []byte(content), 0600); err != nil {
			m.logger.Warn("auto-generated admin credentials — could not write credentials file, set MONSTER_ADMIN_PASSWORD env var",
				"email", email,
				"error", err,
			)
		} else {
			m.logger.Warn("auto-generated admin credentials written to file",
				"path", credPath,
				"email", email,
			)
		}
	} else {
		m.logger.Info("super admin created", "email", email)
	}

	return nil
}

func getEnvOrDefault(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
