package db

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"testing"
)

const (
	concurrentWritesBaselineFile  = "testdata/concurrent_writes_baseline.json"
	concurrentWritesGateWorkers   = 64
	concurrentWritesGateTotalOps  = 1024
	concurrentWritesGateThreshold = 0.10
)

// concurrentWritesBaseline is the JSON shape written to
// internal/db/testdata/concurrent_writes_baseline.json. New fields go at
// the end so old baselines keep parsing.
type concurrentWritesBaseline struct {
	DurationSec     float64 `json:"duration_sec"`
	TotalOps        int     `json:"total_ops"`
	Workers         int     `json:"workers"`
	Errors          int     `json:"errors"`
	P50Microseconds int64   `json:"p50_us"`
	P95Microseconds int64   `json:"p95_us"`
	P99Microseconds int64   `json:"p99_us"`
	// OpsPerSec is derived (TotalOps / DurationSec) but stored for
	// human readability of the committed file.
	OpsPerSec float64 `json:"ops_per_sec"`
}

// TestStore_ConcurrentWrites_BaselineGate exercises the 64-way concurrent
// DeploymentStore.Create fan-out against the single-writer SQLite pool
// (MaxOpenConns(1)) with a fixed op count and compares the resulting p95
// latency against the committed baseline. Fails when current p95 exceeds
// baseline p95 by more than concurrentWritesGateThreshold (10 %).
//
// Run modes:
//
//   - Skipped unless the DM_DB_GATE env var is set — the workload is
//     latency-sensitive and varies across hardware, so the gate is
//     opt-in (mirrors the tests/loadtest pattern). `make test` on a
//     dev laptop stays fast by default.
//   - Set DM_DB_GATE_UPDATE=1 to overwrite the committed baseline with
//     the current run's numbers. Use this after an intentional SQLite
//     tuning change or on a new CI runner class.
//   - Set DM_DB_GATE_VERBOSE=1 to log the full measurement even on
//     success — useful for tracking drift over time.
//
// The baseline file lives at testdata/concurrent_writes_baseline.json.
// It is deliberately NOT auto-generated by tooling — re-capturing it is
// a deliberate act and each move should be explained in the commit
// message.
func TestStore_ConcurrentWrites_BaselineGate(t *testing.T) {
	if os.Getenv("DM_DB_GATE") == "" {
		t.Skip("skipping writers-under-load gate; set DM_DB_GATE=1 to enable (see sqlite_bench_test.go for rationale)")
	}
	if testing.Short() {
		t.Skip("writers-under-load gate skipped in -short mode")
	}

	dir := t.TempDir()
	db, err := NewSQLite(filepath.Join(dir, "gate.db"))
	if err != nil {
		t.Fatalf("NewSQLite: %v", err)
	}
	t.Cleanup(func() { _ = db.Close() })
	appID := bootstrapBenchApp(t, db, "gate")

	// Warm-up: a small run so the WAL, page cache, and goroutine pool
	// are hot before the measurement. Without this the first few ops
	// carry first-transaction cost and inflate p95.
	_ = runConcurrentWrites(t, db, appID, concurrentWritesGateWorkers, concurrentWritesGateWorkers*2)

	stats := runConcurrentWrites(t, db, appID, concurrentWritesGateWorkers, concurrentWritesGateTotalOps)
	if stats.errors > 0 {
		t.Fatalf("CreateDeployment reported %d errors under %d-way contention — queue saturation regression",
			stats.errors, concurrentWritesGateWorkers)
	}

	current := concurrentWritesBaseline{
		DurationSec:     stats.duration.Seconds(),
		TotalOps:        concurrentWritesGateTotalOps,
		Workers:         concurrentWritesGateWorkers,
		Errors:          stats.errors,
		P50Microseconds: stats.p50.Microseconds(),
		P95Microseconds: stats.p95.Microseconds(),
		P99Microseconds: stats.p99.Microseconds(),
	}
	if stats.duration.Seconds() > 0 {
		current.OpsPerSec = float64(concurrentWritesGateTotalOps) / stats.duration.Seconds()
	}

	logLine := fmt.Sprintf("writers-under-load: %d ops / %.2fs, %.0f ops/s, p50=%dµs p95=%dµs p99=%dµs",
		current.TotalOps, current.DurationSec, current.OpsPerSec,
		current.P50Microseconds, current.P95Microseconds, current.P99Microseconds)

	if os.Getenv("DM_DB_GATE_UPDATE") == "1" {
		writeConcurrentWritesBaseline(t, &current)
		t.Logf("%s — baseline UPDATED at %s (DM_DB_GATE_UPDATE=1)", logLine, concurrentWritesBaselineFile)
		return
	}

	baseline, err := readConcurrentWritesBaseline()
	if errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("%s\nno baseline at %s — capture one with DM_DB_GATE=1 DM_DB_GATE_UPDATE=1 go test -run TestStore_ConcurrentWrites_BaselineGate ./internal/db/",
			logLine, concurrentWritesBaselineFile)
	}
	if err != nil {
		t.Fatalf("read baseline %s: %v", concurrentWritesBaselineFile, err)
	}

	// Gate on p95. p50 is too noise-prone on a fan-out where per-op
	// wait time dominates; p99 is dominated by the single worst case
	// (channel scheduling, GC pause, kernel wake-up); p95 is the sweet
	// spot for "did we just make the serialized-write queue tail
	// noticeably longer".
	maxAllowed := float64(baseline.P95Microseconds) * (1 + concurrentWritesGateThreshold)
	if float64(current.P95Microseconds) > maxAllowed {
		t.Fatalf(
			"%s\nP95 REGRESSION: current %dµs > baseline %dµs * (1+%.2f) = %.0fµs\n"+
				"baseline: %d ops / %.2fs, p50=%dµs p95=%dµs p99=%dµs\n"+
				"If this is intentional, update %s via DM_DB_GATE_UPDATE=1.",
			logLine,
			current.P95Microseconds, baseline.P95Microseconds, concurrentWritesGateThreshold, maxAllowed,
			baseline.TotalOps, baseline.DurationSec,
			baseline.P50Microseconds, baseline.P95Microseconds, baseline.P99Microseconds,
			concurrentWritesBaselineFile,
		)
	}

	if os.Getenv("DM_DB_GATE_VERBOSE") == "1" {
		t.Logf("%s — PASSED vs baseline p95=%dµs (%+.0fµs, threshold %.0f%%)",
			logLine, baseline.P95Microseconds,
			float64(current.P95Microseconds-baseline.P95Microseconds),
			concurrentWritesGateThreshold*100)
	}
}

func readConcurrentWritesBaseline() (*concurrentWritesBaseline, error) {
	data, err := os.ReadFile(concurrentWritesBaselineFile)
	if err != nil {
		return nil, err
	}
	var b concurrentWritesBaseline
	if err := json.Unmarshal(data, &b); err != nil {
		return nil, fmt.Errorf("parse %s: %w", concurrentWritesBaselineFile, err)
	}
	return &b, nil
}

func writeConcurrentWritesBaseline(tb testing.TB, b *concurrentWritesBaseline) {
	tb.Helper()
	if err := os.MkdirAll("testdata", 0o755); err != nil {
		tb.Fatalf("mkdir testdata: %v", err)
	}
	data, err := json.MarshalIndent(b, "", "  ")
	if err != nil {
		tb.Fatalf("marshal baseline: %v", err)
	}
	if err := os.WriteFile(concurrentWritesBaselineFile, append(data, '\n'), 0o644); err != nil {
		tb.Fatalf("write %s: %v", concurrentWritesBaselineFile, err)
	}
}
